theme: jekyll-theme-minimal
title: Financial Immunology: Dynamics and Contagion in the NASDAQ Market
description: ADAV Project
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
    - title: Home
    url: /
  - title: Example
    url: example
